DROP TABLE IF EXISTS PROFESORES;

CREATE TABLE PROFESORES (
  ID_PROFESOR INT(11) NOT NULL AUTO_INCREMENT,
  NOMBRE_PROFESOR VARCHAR(150) NOT NULL,
  PRIMARY KEY (ID_PROFESOR)
);

DROP TABLE IF EXISTS CURSOS;
CREATE TABLE CURSOS (
  ID_CURSO int(11) NOT NULL AUTO_INCREMENT,
  NIVEL_CURSO varchar(20) NOT NULL,
  HORAS_CURSO int(3) NOT NULL,
  TITULO_CURSO varchar(200)  NOT NULL,
  ACTIVO_CURSO int(1) NOT NULL,
  ID_PROFESOR int(11) NOT NULL,
  PRIMARY KEY (ID_CURSO),
  CONSTRAINT ID_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES profesores (ID_PROFESOR) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PROFESORES (NOMBRE_PROFESOR) VALUES('ZINEDINE ZIDANE');
INSERT INTO PROFESORES (NOMBRE_PROFESOR) VALUES('LADY BUG');
INSERT INTO PROFESORES (NOMBRE_PROFESOR) VALUES('KURK KOBAIN');
INSERT INTO PROFESORES (NOMBRE_PROFESOR) VALUES('ESTANISLAO KUBALA');
INSERT INTO PROFESORES (NOMBRE_PROFESOR) VALUES('EL CANSINO');
INSERT INTO PROFESORES (NOMBRE_PROFESOR) VALUES('PINKY TWIN');

INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'QUIMICA FISICA 1',1,1);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',50,'QUIMICA ANALITICA 1',1,2);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'QUIMICA ORGANICA 1',1,3);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'CIENCIA DE LOS MATERIALES',0,4);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'QUIMICA INORGANICA',1,5);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',25,'MATEMATICAS 1',1,6);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('AVANZADO',120,'FISICA QUIMICA AVANZADA 1',0,5);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'ESCALAR SIN CUERDA',1,1);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',320,'MANEJO DE KUAMIS',1,2);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'PRINCIPIOS SOLID',1,3);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'APRENDE MYBATIS',1,4);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',160,'ANGULAR FRONT',1,5);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'SPRING BOOT BOOT BOOT',0,6);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'PRIMAVERA',1,1);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'CUCUMBER',1,2);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'QUIMICA 3',0,3);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'QUIMICA FISICA 11',0,4);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',160,'PROGRAMACION AVANZADA',1,6);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'STRUTS',1,6);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'KIBANA',0,1);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',160,'ELASTICSEARCH',1,2);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'LINUX',0,3);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'APACHE',1,4);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',160,'DOCKERS',0,5);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',120,'PROTRACTOR',1,6);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'JAMINE Y KARMA',0,1);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('MEDIO',160,'JENKINS',1,4);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'MERCURIAL',0,1);
INSERT INTO CURSOS (NIVEL_CURSO,HORAS_CURSO,TITULO_CURSO,ACTIVO_CURSO,ID_PROFESOR) VALUES('BASICO',120,'QUIMICA FISICA 23',1,1);