DROP TABLE IF EXISTS profesores

CREATE TABLE profesores (
  ID_PROFESOR INT(11) NOT NULL AUTO_INCREMENT,
  NOMBRE_PROFESOR VARCHAR(150) NOT NULL,
  PRIMARY KEY (ID_PROFESOR)
);

DROP TABLE IF EXISTS cursos
CREATE TABLE cursos (
  ID_CURSO int(11) NOT NULL AUTO_INCREMENT,
  NIVEL_CURSO varchar(20) NOT NULL DEFAULT 'MEDIO',
  HORAS_CURSRSO int(3) NOT NULL DEFAULT '10',
  TITULO_CURSO varchar(200) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  ACTIVO_CURSO int(1) NOT NULL DEFAULT '1',
  ID_PROFESOR int(11) NOT NULL,
  PRIMARY KEY (ID_CURSO),
  KEY ID_PROFESOR_idx (ID_PROFESOR),
  CONSTRAINT ID_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES profesores (ID_PROFESOR) ON DELETE CASCADE ON UPDATE CASCADE
);